display_name: Keyviz
package_name: keyviz
icon: assets/logo.png
generic_name: Keypress Visualizer
categories:
  - Development
  - Utility
startup_notify: true

license: GPL-3.0
vendor: zetaloop
packager: zetaloop
packagerEmail: zetaloop@outlook.com
url: https://github.com/zetaloop/keyviz
